### ISSUE TITLE
Breakpoints tracking issue

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#1977]
#### Functionality
* Position
    * [x] [+] Fixed address with rebase (can be initially specified as expression calculated once)
    * [ ] [R?] named or expression - more reusable, function in a module that isn't loaded yet, other uses
    * [ ] [R?] Module relative offset (when does r2 calculate it?)
        * Similar to the point above but for modules (dll, share libs)
    * [ ] [R-] source code, debug information based
        * PDB info is not really working on r2? (need to check and open an issue)
        * Is this integrated with flags or requires a special command
    * [ ] [R-/C-] asm regex? Maybe it could be done by genearating breakpoints from search results or selection in any addressable item widget. - Can use existing r2 search just need to integrate it with breakpoints on r2's or cutter's side
        * Suggestion + TODO: Support multiple selection in Search widget and apply several actions to the selected addresses (e.g add breakpoints)
* Type
    * [x] [+] software
    * [ ] [R*] hardware
        * [+] RWX
        * [C-] size
        * [ ] [R*] some kind of UI indicator when count limit is exceeded. How to get info? - have to manually parse drx output
* Conditional
    * [ ] [R?] evaluated in R2
    * [ ] [R-] (low priority) Evaluated in debugger? Can we ask gdbserver to evaluate complex c++ expression? Saves remote debugger bandwidth.
        * Breakpoint conditions can be evaluated on gdb target’s side if the target supports it. Instead of evaluating the conditions locally, GDB encodes the expression into an agent expression (see [Agent Expressions](https://sourceware.org/gdb/onlinedocs/gdb/Agent-Expressions.html#Agent-Expressions)) suitable for execution on the target, independently of GDB. Global variables become raw memory locations, locals become stack accesses, and so forth.
    * Which parts are affected by condition (break, trace, custom cmd, hitcount)?
    * [ ] [R-] thread specific - could be done as exmaple condition instead inside r2
* Temporary disable
    * [x] [+] Fixed. ~~It seems that r2 currently does it only partially. What happens with extra features.~~
* [ ] [R?] hit count - r2 state unclear
    * [R-] ignore first x hits
    * [R-] ignore after x hits
    * [R-] one time - deletes completley
    * [R-] debugger side?
        * Low priority - could be useful to save bandwidth when working with remote debuggers and not too hard to implement
* Action on hit
    * [ ] [R*] break/continue after hit - (can't disable separately from trace)
    * [ ] [R*] tracepoint (currently disables break)
    * [ ] [R+] r2 command
    * [ ] [?] tracing mode - need to clarify r2 functionality. Special buttons not necesarry (but nice to have) if tracing mode can be enabled using r2 command action.
        * Need to clarify what it is and how it should be used
    * [ ] [R-] External plugin callback
        * gdb-style static probe points - when the current PC is at the probe’s location you can setup SystemTap and DTrace probes. Supposed to be very light for tracing various data
        * This is something that should be discussed with r2devs
* [ ] [R?] Special break conditions - based on r2 capabilities (some of these break without being breakpoints)
    * [ ] [R*?] Initial break on restart
    * [ ] [R-] (Low priority) exceptions (throw/rethrow/catch/uncaught) - is anything feasable without a lot of language specific code? Minimum of CPP would still be useful
        
    * [ ] [R*?] thread and process events - based on debugger and r2 capabilities
    * [ ] dynamic library events
    * [ ] [R*?] syscalls
    * [ ]  Known error handling, panic functions
    * [ ] [R*?] non return functions - not sure if r2 implements it as condition or generates once
    * [ ] [R*?] dbg.bep break on entry
    * [ ] [R*?] dbg.aftersyscall - conflicting descriptions
    * [ ] [R*?]dbg.bpsysign ignore system breakpoints
    * [ ] [R*?] dbg.clone Stop execution if new thread is created
    * [ ] [R*?] dbg.consbreak ? SIGINT handle for attached processes
    * [ ] [R*?] dbg.execs: Stop execution if new thread is created
    * [ ] [R*?] dbg.forks: Stop execution if fork() is done (see dbg.threads)
    * [ ] [R*?] dbg.unlibs: If set stop when unloading matching libname
#### UI
* Disassembly widget
    * [x] [+] indicate breakpoints
    * [x] [+] keyboard shortcut for setting basic breakpoint
    * [ ] [C*] context menu for basic breakpoint operations, doesn't need to contain everything - only available outside of debug mode atm
        * [x] [+] Add, remove
        * [ ] [C-] Edit or Add advanced depending on current line containing breakpoint
        * [ ] [C-] Open breakpoint dialog
* Breakpoint widget
    * [x] [+] List all breakpoints
    * [ ] [C-] Two groups bp groups:
        * [x] regular breakpoints 
        * [ ] other break conditions (bep, new thread, loading library, ...)
    * Display
        * [ ] [C-] Red circle icon for indicating enable state (- Lamp?)
        * [x] [+] Address
        * [ ] [C-/R-] Position - function with offset possibly module, position expression
        * [ ] [C-] Tooltip/preview
        * [x] [+] Enable/Disable state
        * [ ] [C-] Type sw, hw, could be merged with hw watchpoint permissions
        * [ ] [C-] Presence of condition or command
    * [x] [+] Easy way for toggling breakpoint enable state
    * [x] [+] Allow add, delete, toggle
    * [x] [+] Support delete and toggle for multiple row selection
    * [x] [+] Addressable item functionality
    * [ ] [C-]  #1975 Use new/edit breakpoint dialog
* [ ] [C-] #1975 New/Edit breakpoint dialog
    * [ ] Dialog for editing all breakpoint options
    * [ ] Position (multiple kind)
    * [ ] Type sw or hw, hw breakpoint config
    * [ ] Action when breakpoint is triggered (see functionality section)
        * [ ] command
    * [ ] Condition (include help or example)

* Decompiler widget
    * [x] [+] indicate lines with breakpoints
    * [ ] set basic sw breakpoint

**Comment by karliss** [comment]
Related r2 issue https://github.com/radareorg/radare2/issues/1225

**Comment by ITAYC0HEN** [comment]
@karliss I thing this had progress we can resolve some of the checkboxes. Also #1935 can probably be closed, right?
