### ISSUE TITLE
[META] Backtrace tracking issue

### ISSUE THREAD

**Issue by yossizap** [radareorg/cutter#1992]
- Information output
    - [ ] Address information
    - [ ] Function name+offset
    - [ ] Module name
    - [ ] Function names from loaded dynamic libraries
    - [ ] Function parameters list with values similar to gdb/lldb output
    - [ ] Thread stop reason (lldb, gdb)
- Enhancements
    - [ ] Easy way of viewing each position in disassembly view
    - [ ] Optional alternative to the current stack 
    - [ ] Add an option to search the entire stack to find possible return addresses
    - [ ] Make other threads' backtrace more accessible instead of only showing the current thread - options to show backtrace of all threads, show backtrace of thread X, etc. 
- Current unintended behavior
    - [ ] Double clicking a cell will edit it (shouldn't eb editable)
