### ISSUE TITLE
[META] Stack view tracking issue

### ISSUE THREAD

**Issue by yossizap** [radareorg/cutter#1993]
- Telescoping 
     - [ ] [C*] Currently slows down out debugging sessions on Cutter
     - [ ] [C*] Better formatting of the telescoping - column for each ref/expandable arrows
- Interaction
     - [ ] [R-] Push and Pop [Q\D]Words from\to the stack (Worth consider adding multiple values to the stack and not only one)
     - [ ] [C-] Edit stack values - refs included?
- Enhancements
     - [ ] [R-] View frames, local variables, type information
- [ ] Highlight the SP
- [ ] Jump to SP or BP
- [ ] Something similar to the "Suspend call stack" feature in x64dbg, currently it only freezes the GUI display, are we interested in preventing any actions on the stack itself?
- [ ] [C-] Synchronize memory widget with register (RSP, RBP, ...)
