### ISSUE TITLE
[META] Register tracking issue

### ISSUE THREAD

**Issue by yossizap** [radareorg/cutter#1996]
- Read/Write
    - [x] Read/write general purpose registers
    - [ ] [C-/R*] read vector registers - Nothing is available for zmm registers yet and drml/drmf, drmyq(ymm) aren't ideal, it's probably best to use drt 'xmm/fpu/ymm' and format it ourselves
    - [ ] [R*] Write vector registers
- Telescoping
    - [ ] [C-/R-] Solve the performance issues by using async fetching of values
    - [ ] [C*] Colormap (see the [Dereferencing](https://github.com/danigargu/deREferencing) plugin for IDA)
    - [ ] [C*] Improve output - column for each ref/expandable arrows
- Enhancements
    - [ ] [C-] Show flags
    - [ ] [C-] Toggle flags
    - [ ] [C*] Navigate in memory views - right click sub-submenu is the only way right now
    - [ ] [C-] Add different display options (hex, dec, float, double)
        - [ ] [R-?] Array format for vector registers
    - [ ] [C-] Highlight registers that changed in the previous step
Remote
    - [ ] [R-] Properly unpack struct flags from gdbr target xml to show full fpu flag info
    - [ ] [C-] Get registers comment (drC) via tooltip
        - [ ] [R*] Improve r2 descriptions
    - [ ] [C-] Add an option to copy the entire register view
    - [ ] [C-] Double click to seek
    - [ ] [C-] Right click -> Highlight to highlight tokens across all disassembly (and graph) views - permanent colored highlight in addition to the regular highlight
