### ISSUE TITLE
[META] Memory map tracking issue

### ISSUE THREAD

**Issue by yossizap** [radareorg/cutter#2008]
Right click options:
* [ ] [R?] Allocate/free memory
* [ ] [C-/R?] Set memory page permissions
* [ ] [C-] Dump memory
* [ ] [R?] Add virtual module
* [ ] [R?] Set HW breakpoint of custom size on the selected map
* [ ] [R*] Rebase map to a different address
    * Should also let you to patch all the references to that section
* [ ]  [C-] Analyze loaded maps
* [ ]  [C-] Download pdb for the selected lib

Enhancements:
* [ ]  [C-] Double clicking on heap/stack should jump to heap(isn't available yet)/stack widget
* [ ]  [C-] Add section info for each loaded lib using `dmS`
