### ISSUE TITLE
[TRACKER] Some HexdumpWidget UI features request

### ISSUE THREAD

**Issue by pelijah** [radareorg/cutter#64]
- [ ] Change format words, dwords, qwords, ..(pxh, pxw, pxq) on right click (see px?)
- [ ] Scrolling by line
- [ ] hex.compact
- [ ] hex.comments (pxc command)
- [ ] hex.pairs (it's set to false by default in cutter, but we should make it configurable for the user)
- [ ] Use same disassembly architecture in parsing panel as the one used by the opened file by default
- [ ] Hashes configurable in Hexdump -> information -> bytes info
- [ ] Endianess
- [ ] Colors hexdump
- [ ] Implement write operations (`wo?`) (see #715) 

---

- [x] Add ability to always align (like now aligned on 0) or never align (stand at current seek)
- [x] Show where current seek it
- [x] show flags (pxa command) (not compatible-yet with hex.compact radare/radare2#8957)
- [x] Hexdump is too wide #149
- [x] Place separators between areas to visually split them
- [x] Synchronize selection for hex-data and ASCII areas
- [x] Change number of columns on right click hex.cols
- [x] Add a button to close the side bar of the hexdump (see #636)
- [x] Add "right Click > Select Block" to the Hex Widget (see #761)

**Comment by nezza** [comment]
- [ ] Use same disassembly architecture as is used by the file by default

**Comment by xarkes** [comment]
Cf https://github.com/radareorg/cutter/pull/235

**Comment by xarkes** [comment]
Updated, added two items.

**Comment by kernelm0de** [comment]
> Add a button to close the side bar of the hexdump
Any details where the button needs to be added?. I think it would be better toggling the sideview from context menu of hexdump.

**Comment by ITAYC0HEN** [comment]
it is up to you. Toggle button is good. (Click>close-menu, Click>open_menu)

**Comment by radare** [comment]
See https://github.com/radareorg/cutter/issues/925

**Comment by radare** [comment]
See https://github.com/radareorg/cutter/issues/295

**Comment by Maijin** [comment]
Splitted issues.
