### ISSUE TITLE
[META] Better disasm output

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#774]
As discussed around, the disasm output is sometimes not easy to read. This issue regroups the stuff we want to improve for better output.

- [x] Function names/calls (See https://github.com/radareorg/cutter/pull/519)
- [x] Shrink flag names (Sometimes long strings make the box very wide)
- [x] Automatically disable `aan` which can be very misleading

Feel free to edit or comment to add stuff.

**Comment by Maijin** [comment]
Removing the `aan` must be done once PE analysis is fixed otherwise you'll face a huge backward on many PE binaries and loose user-base in profit of other tools that don't have this problem.

**Comment by Maijin** [comment]
ok for the aan it's done now

**Comment by ITAYC0HEN** [comment]
@Maijin is this split already?

**Comment by Maijin** [comment]
Nop are you doing it?

**Comment by NirmalManoj** [comment]
> * [ ]  Function names/calls (See #519)
> * [ ]  Shrink flag names (Sometimes long strings make the box very wide)
> * [x]  Automatically disable `aan` which can be very misleading

Is the last part done? What all things are left in this issue? I was thinking about adding this to my gsoc proposal for "Diffing mode" as better disasm output is relevant to the task. But from the discussion about this in the pr linked (PR #519), I see this task has to be finished in a more global from level from Radare. 

So I would like to know if there are any plans to do this summer as part of gsoc of some other project, or if not, is this something I can work on? My focus is on diffing mode project. Hence, I want to know the things which should be finished in radare2 to work on this.
