### ISSUE TITLE
[TRACKER] Text highlighter: bugs & feature requests

### ISSUE THREAD

**Issue by pelijah** [radareorg/cutter#97]
* [ ] Scrolling changes selection within initial line
* [ ] Scrolling resets selection when initial line becomes nonvisible
* [x] It highlights given text with additional symbols
* [x] Highlight color stronger
* [x] Highlight in Graph
* [x] It is not works on the first instruction of function.
* [x] It almost always selects only second operand of instruction.
* [x] Sometimes it selects comma between operands, brackets from operand or even text from comment string.

**Comment by pelijah** [comment]
Someone has fixed some problems. I added another 2.

**Comment by Maijin** [comment]
I added some more too

**Comment by pelijah** [comment]
Moved to #1241 #1242
